<a href="https://colab.research.google.com/github/DevyanshBhattacharya/Self_Attention_for_transformer/blob/main/Self_Attention_For_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Implementation of Self Attention for Transformer


In [1]:
import math
import numpy as np

In [2]:
L,d_k,d_v=4,8,8

In [3]:
q=np.random.randn(L,d_k)
k=np.random.randn(L,d_k)
v=np.random.randn(L,d_v)


In [4]:
dat=np.matmul(q,k.T)

In [5]:
print(dat)

[[-0.55068466 -0.30532631  2.22327018  0.15348076]
 [-0.34141603  0.58365185 -0.60743513  2.75668439]
 [ 4.55196523  0.40655709  0.41729617  0.37503636]
 [-1.36929812 -3.46002949 -1.5613903  -2.24188381]]


In [6]:
#Reducing the varience
scale=np.matmul(q,k.T)/math.sqrt(d_k)

In [7]:
#Masking the unrequired Data
mask=np.tril(np.ones((L,L)))
mask[mask==0]= -np.infty
mask[mask==1]=0

In [8]:
print(scale+mask)

[[-0.19469643        -inf        -inf        -inf]
 [-0.12070879  0.20635209        -inf        -inf]
 [ 1.60936274  0.14373964  0.14753648        -inf]
 [-0.48411999 -1.22330516 -0.55203484 -0.79262562]]


In [9]:
#Applying softmax ( Converts a vector to a probability Distribution)
def softmax(x):
  return np.exp(x).T/np.sum(np.exp(x),axis=1).T


In [10]:
attention=softmax(scale+mask)

In [11]:
print(attention)

[[1.         0.41895593 0.68364542 0.31782489]
 [0.         0.58104407 0.15787701 0.15176229]
 [0.         0.         0.15847758 0.29695652]
 [0.         0.         0.         0.23345631]]


In [12]:
final=np.matmul(attention,v)
print(final)

[[-0.29594994 -0.1865571   0.58733192 -1.21841616 -1.14723966  0.96137414
   1.41526331 -1.85001196]
 [ 0.41981393 -0.32840733  0.27880021 -0.45518128 -0.34227197  0.36229035
   0.30470302 -1.42937328]
 [ 0.0318883  -0.18176105  0.1090823  -0.38199891 -0.21641224 -0.20047033
  -0.25273314  0.20824458]
 [ 0.01236915 -0.21676391  0.06747611 -0.20794148 -0.19911519 -0.13583799
  -0.16122204  0.32762608]]
